name = "XCALibre"
uuid = "cf91e36b-bd94-493a-8848-32508a10963c"
authors = ["Humberto <h.medina@aerofluids.org>"]
version = "0.3.3-DEV"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
ILUZero = "88f59080-6952-5380-9ea5-54057fb9a43f"
IncompleteLU = "40713840-3770-5561-ab4c-a76e7d0d7895"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
KrylovPreconditioners = "45d422c2-293f-44ce-8315-2cb988662dec"
LDLFactorizations = "40e66cde-538c-5869-a4ad-c39174c6795b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseMatricesCSR = "a0a7dd2c-ebf4-11e9-1f05-cf50bc540ca1"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
XCALibre_AMDExt = "AMDGPU"
XCALibre_CUDAExt = "CUDA"

[compat]
AMDGPU = "1"
Accessors = "0.1.30"
Adapt = "4.0"
Atomix = "0.1, 1"
CUDA = "5"
GPUArrays = "10.2, 11"
ILUZero = "0.2"
IncompleteLU = "0.2"
KernelAbstractions = "0.9.25"
Krylov = "0.9"
KrylovPreconditioners = "0.3"
LDLFactorizations = "0.10"
LinearOperators = "2.8"
PrecompileTools = "1.2"
ProgressMeter = "1.10"
Reexport = "1.2"
Setfield = "1.1"
SparseMatricesCSR = "0.6"
StaticArrays = "1.9"
Statistics = "1"
julia = "1.8"
